import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Copy, Loader2, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { confirmCashPayment, getPendingCashPayments, lookupCashPayment, reissueCashPaymentCode, type CashPayment, type CashPaymentStatus } from '../../services/cashPayments.service';

const formatMoney = (cents: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
const formatDate = (date: string | null) => date ? new Intl.DateTimeFormat('es-EC', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Guayaquil' }).format(new Date(date)) : '—';
const statusLabel: Record<CashPaymentStatus, string> = { PENDING: 'Pendiente', CONFIRMED: 'Confirmado', CANCELLED: 'Cancelado', REFUNDED: 'Reembolsado', EXEMPTED: 'Exento' };

function PaymentDetails({ payment }: { payment: CashPayment }) {
  return <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-3 text-sm rounded-xl bg-slate-50 border border-slate-100 p-4">
    <p><span className="text-slate-500">Paciente:</span> <strong className="text-slate-800">{payment.patient.displayName}</strong></p>
    <p><span className="text-slate-500">Médico:</span> <strong className="text-slate-800">{payment.doctor.displayName}</strong></p>
    <p><span className="text-slate-500">Clínica:</span> <strong className="text-slate-800">{payment.clinic.name}</strong></p>
    <p><span className="text-slate-500">Servicio:</span> <strong className="text-slate-800">{payment.appointment.serviceName}</strong></p>
    <p><span className="text-slate-500">Cita:</span> <strong className="text-slate-800">{formatDate(payment.appointment.startsAt)}</strong></p>
    <p><span className="text-slate-500">Importe:</span> <strong className="text-emerald-700">{formatMoney(payment.amountCents)}</strong></p>
    <p><span className="text-slate-500">Estado:</span> <strong className="text-slate-800">{statusLabel[payment.status]}</strong></p>
  </div>;
}

export default function CashPaymentsView() {
  const [code, setCode] = useState(''); const [payment, setPayment] = useState<CashPayment | null>(null);
  const [pending, setPending] = useState<CashPayment[]>([]); const [loadingPending, setLoadingPending] = useState(true);
  const [isLookingUp, setIsLookingUp] = useState(false); const [isConfirming, setIsConfirming] = useState(false); const [isReissuing, setIsReissuing] = useState(false);
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const [showConfirm, setShowConfirm] = useState(false); const [showReissue, setShowReissue] = useState(false); const [reason, setReason] = useState(''); const [newCode, setNewCode] = useState<string | null>(null);
  const [filters, setFilters] = useState({ date: '', patient: '', doctorId: '', clinicId: '', status: '' });

  const query = useMemo(() => ({ ...(filters.date ? { date: filters.date } : {}), ...(filters.patient ? { patient: filters.patient } : {}), ...(filters.doctorId ? { doctorId: filters.doctorId } : {}), ...(filters.clinicId ? { clinicId: filters.clinicId } : {}), ...(filters.status ? { status: filters.status as CashPaymentStatus } : {}) }), [filters]);
  const loadPending = async () => { setLoadingPending(true); try { setPending(await getPendingCashPayments(query)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudieron cargar los pagos pendientes.'); } finally { setLoadingPending(false); } };
  useEffect(() => { void loadPending(); }, [query]);

  const lookup = async () => { if (!code.trim()) return setError('Ingresa el código entregado al paciente.'); setIsLookingUp(true); setError(null); setMessage(null); setNewCode(null); try { setPayment(await lookupCashPayment(code)); } catch (caught) { setPayment(null); setError(caught instanceof Error ? caught.message : 'No se encontró un pago disponible.'); } finally { setIsLookingUp(false); } };
  const confirm = async () => { if (!payment) return; setIsConfirming(true); setError(null); try { const idempotencyKey = globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`; const confirmed = await confirmCashPayment(payment.paymentId, code, idempotencyKey); setPayment(confirmed); setMessage('Pago confirmado. La cita y la confirmación del paciente no fueron modificadas.'); setShowConfirm(false); await loadPending(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo confirmar el pago.'); } finally { setIsConfirming(false); } };
  const reissue = async () => { if (!payment) return; setIsReissuing(true); setError(null); try { const reissued = await reissueCashPaymentCode(payment.paymentId, reason.trim()); setPayment(reissued); setNewCode(reissued.code); setCode(''); setShowReissue(false); setReason(''); setMessage('Código reemitido. El código anterior ya no funcionará.'); await loadPending(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo reemitir el código.'); } finally { setIsReissuing(false); } };
  const selectPending = (selected: CashPayment) => { setPayment(selected); setCode(''); setMessage('Ingresa el código del paciente para confirmar este pago.'); setError(null); window.scrollTo({ top: 0, behavior: 'smooth' }); };

  return <div className="space-y-6">
    <div><h1 className="text-2xl font-semibold tracking-tight text-slate-900">Pagos en efectivo</h1><p className="text-sm text-slate-500 mt-1">Busca el código del paciente y registra la recepción de efectivo.</p></div>
    {error && <div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />{error}</div>}
    {message && <div className="flex gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 className="w-4 h-4 shrink-0 mt-0.5" />{message}</div>}
    <section className="bg-white border border-slate-100 rounded-2xl p-5 shadow-sm space-y-4">
      <div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-sky-600" /><h2 className="font-semibold text-slate-900">Confirmar pago en efectivo</h2></div>
      <div className="flex flex-col sm:flex-row gap-2"><input value={code} onChange={event => setCode(event.target.value.toUpperCase())} onKeyDown={event => { if (event.key === 'Enter') void lookup(); }} placeholder="Ej. Z7K9-M4QP" className="flex-1 rounded-xl border border-slate-200 px-3 py-2.5 font-mono uppercase tracking-wider focus:outline-none focus:ring-2 focus:ring-sky-200" /><button onClick={() => void lookup()} disabled={isLookingUp} className="inline-flex justify-center items-center gap-2 rounded-xl bg-sky-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{isLookingUp ? <Loader2 className="w-4 h-4 animate-spin" /> : <Search className="w-4 h-4" />}Buscar pago</button></div>
      {payment && <div className="space-y-4"><PaymentDetails payment={payment} />
        {payment.status === 'PENDING' ? <div className="flex flex-wrap gap-2"><button onClick={() => setShowConfirm(true)} disabled={!code || isConfirming} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">Registrar efectivo recibido</button><button onClick={() => setShowReissue(true)} disabled={isReissuing} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700"><RefreshCw className="w-4 h-4" />Reemitir código</button></div> : <p className="text-sm text-slate-500">Este pago ya no admite confirmación ni reemisión.</p>}
      </div>}
      {newCode && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-semibold text-amber-900">Nuevo código: <span className="font-mono tracking-widest">{newCode}</span></p><p className="text-xs text-amber-800 mt-1">Muéstralo una sola vez al solicitante. El código anterior fue invalidado.</p><button onClick={() => { navigator.clipboard?.writeText(newCode).catch(() => undefined); }} className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-amber-900"><Copy className="w-3 h-3" />Copiar</button></div>}
    </section>
    <section className="bg-white border border-slate-100 rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-100 flex flex-col gap-3"><div><h2 className="font-semibold text-slate-900">Pagos pendientes</h2><p className="text-xs text-slate-500 mt-1">Selecciona un pago e ingresa siempre el código del paciente para confirmarlo.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-2"><input type="date" value={filters.date} onChange={event => setFilters(value => ({ ...value, date: event.target.value }))} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input value={filters.patient} onChange={event => setFilters(value => ({ ...value, patient: event.target.value }))} placeholder="Filtrar paciente" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input value={filters.doctorId} onChange={event => setFilters(value => ({ ...value, doctorId: event.target.value }))} placeholder="ID de médico" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input value={filters.clinicId} onChange={event => setFilters(value => ({ ...value, clinicId: event.target.value }))} placeholder="ID de clínica" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><select value={filters.status} onChange={event => setFilters(value => ({ ...value, status: event.target.value }))} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Pendientes</option><option value="PENDING">Pendientes</option></select></div></div>
      {loadingPending ? <div className="p-8 text-sm text-slate-500 flex gap-2"><Loader2 className="w-4 h-4 animate-spin" />Cargando pagos…</div> : pending.length === 0 ? <div className="p-8 text-sm text-slate-500">No hay pagos pendientes en este alcance.</div> : <div className="divide-y divide-slate-100">{pending.map(item => <button key={item.paymentId} onClick={() => selectPending(item)} className="w-full text-left p-4 hover:bg-slate-50 transition-colors"><div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:justify-between"><div><p className="font-semibold text-slate-800">{item.patient.displayName} · {item.appointment.serviceName}</p><p className="text-xs text-slate-500 mt-1">{formatDate(item.appointment.startsAt)} · {item.doctor.displayName} · {item.clinic.name}</p></div><strong className="text-emerald-700">{formatMoney(item.amountCents)}</strong></div></button>)}</div>}
    </section>
    {showConfirm && payment && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h3 className="text-lg font-semibold">¿Confirmar efectivo recibido?</h3><p className="text-sm text-slate-600 mt-2">Registrarás {formatMoney(payment.amountCents)} para {payment.patient.displayName}. Esta acción no modifica la cita.</p><div className="mt-5 flex gap-3 justify-end"><button onClick={() => setShowConfirm(false)} className="px-4 py-2 text-sm font-semibold text-slate-600">Cancelar</button><button onClick={() => void confirm()} disabled={isConfirming} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{isConfirming ? 'Confirmando…' : 'Confirmar pago'}</button></div></div></div>}
    {showReissue && payment && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h3 className="text-lg font-semibold">Reemitir código</h3><p className="text-sm text-slate-600 mt-2">El código anterior dejará de funcionar. Registra el motivo de la reemisión.</p><textarea value={reason} onChange={event => setReason(event.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Ej. El paciente no recibió el código" /><div className="mt-5 flex gap-3 justify-end"><button onClick={() => setShowReissue(false)} className="px-4 py-2 text-sm font-semibold text-slate-600">Cancelar</button><button onClick={() => void reissue()} disabled={!reason.trim() || isReissuing} className="rounded-xl bg-sky-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{isReissuing ? 'Reemitiendo…' : 'Reemitir código'}</button></div></div></div>}
  </div>;
}
