import { useEffect, useState } from 'react';
import { AlertCircle, BarChart3, Loader2, RefreshCw } from 'lucide-react';
import { getFinancePayments, getFinanceSummary, type FinanceGroup, type FinancePaymentsPage, type FinanceSummary } from '../../services/finance.service';

const money = (cents: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
const date = (value: string | null) => value ? new Intl.DateTimeFormat('es-EC', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Guayaquil' }).format(new Date(value)) : '—';
function GroupTable({ title, groups }: { title: string; groups: FinanceGroup[] }) { return <div className="bg-white border border-slate-100 rounded-2xl overflow-hidden shadow-sm"><h3 className="px-4 py-3 font-semibold text-slate-800 border-b border-slate-100">{title}</h3>{groups.length ? <div className="divide-y divide-slate-50">{groups.map(group => <div key={group.key} className="px-4 py-3 flex items-center justify-between gap-4 text-sm"><span className="truncate text-slate-600">{group.label}</span><span className="shrink-0 text-right"><strong className="text-emerald-700">{money(group.confirmedCashCents)}</strong><small className="block text-slate-400">{group.paymentCount} pagos</small></span></div>)}</div> : <p className="p-4 text-sm text-slate-500">Sin registros.</p>}</div>; }

export default function FinanceView() {
  const [summary, setSummary] = useState<FinanceSummary | null>(null); const [payments, setPayments] = useState<FinancePaymentsPage | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [filters, setFilters] = useState({ startDate: '', endDate: '', doctorId: '', clinicId: '' });
  const load = async () => { setLoading(true); setError(null); try { const query = { ...(filters.startDate ? { startDate: filters.startDate } : {}), ...(filters.endDate ? { endDate: filters.endDate } : {}), ...(filters.doctorId ? { doctorId: filters.doctorId } : {}), ...(filters.clinicId ? { clinicId: filters.clinicId } : {}) }; const [nextSummary, nextPayments] = await Promise.all([getFinanceSummary(query), getFinancePayments(query)]); setSummary(nextSummary); setPayments(nextPayments); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo cargar la información financiera.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const metricCards = summary ? [
    ['Ingresos registrados', summary.metrics.confirmedCashCents, 'text-emerald-700 bg-emerald-50'], ['Pagos pendientes', summary.metrics.pendingCashCents, 'text-amber-700 bg-amber-50'], ['Pagos cancelados', summary.metrics.cancelledCashCents, 'text-slate-700 bg-slate-100'], ['Requiere revisión', summary.metrics.requiresReviewCents, 'text-rose-700 bg-rose-50'], ['Pagos confirmados', summary.metrics.confirmedPaymentCount, 'text-sky-700 bg-sky-50'], ['Promedio confirmado', summary.metrics.averageConfirmedPaymentCents, 'text-indigo-700 bg-indigo-50'],
  ] as const : [];
  return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight text-slate-900">Ingresos registrados</h1><p className="text-sm text-slate-500 mt-1">Pagos en efectivo declarados como recibidos por el consultorio.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 disabled:opacity-60"><RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />Actualizar</button></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2"><input type="date" value={filters.startDate} onChange={event => setFilters(value => ({ ...value, startDate: event.target.value }))} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><input type="date" value={filters.endDate} onChange={event => setFilters(value => ({ ...value, endDate: event.target.value }))} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><input value={filters.doctorId} onChange={event => setFilters(value => ({ ...value, doctorId: event.target.value }))} placeholder="ID de médico" className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><input value={filters.clinicId} onChange={event => setFilters(value => ({ ...value, clinicId: event.target.value }))} placeholder="ID de clínica" className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><button onClick={() => void load()} className="sm:col-span-2 lg:col-span-4 rounded-xl bg-sky-500 px-4 py-2 text-sm font-semibold text-white">Aplicar filtros</button></div>
    {error && <div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="w-4 h-4 shrink-0" />{error}</div>}
    {loading ? <div className="py-16 flex justify-center gap-2 text-sm text-slate-500"><Loader2 className="w-4 h-4 animate-spin" />Cargando ingresos registrados…</div> : summary && <><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">{metricCards.map(([label, value, colors]) => <div key={label} className={`rounded-2xl p-5 ${colors}`}><p className="text-sm font-medium">{label}</p><p className="mt-2 text-2xl font-bold">{label === 'Pagos confirmados' ? value : money(value)}</p>{label === 'Pagos pendientes' && <p className="mt-1 text-xs">{summary.metrics.pendingPaymentCount} pagos</p>}</div>)}</div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><GroupTable title="Por día" groups={summary.groups.byDay} /><GroupTable title="Por médico" groups={summary.groups.byDoctor} /><GroupTable title="Por clínica" groups={summary.groups.byClinic} /><GroupTable title="Por servicio" groups={summary.groups.byService} /></div>
      <section className="bg-white border border-slate-100 rounded-2xl overflow-hidden shadow-sm"><div className="p-4 border-b border-slate-100 flex gap-2"><BarChart3 className="w-5 h-5 text-sky-600" /><div><h2 className="font-semibold text-slate-800">Pagos registrados</h2><p className="text-xs text-slate-500">{payments?.total || 0} resultados dentro de tu alcance.</p></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr>{['Fecha', 'Paciente', 'Médico', 'Clínica', 'Servicio', 'Importe', 'Estado'].map(header => <th key={header} className="px-4 py-3 font-medium">{header}</th>)}</tr></thead><tbody>{payments?.items.map(item => <tr key={item.paymentId} className="border-t border-slate-50"><td className="px-4 py-3 whitespace-nowrap">{date(item.date)}</td><td className="px-4 py-3">{item.patient.displayName}</td><td className="px-4 py-3">{item.doctor.displayName}</td><td className="px-4 py-3">{item.clinic.name}</td><td className="px-4 py-3">{item.service.name}</td><td className="px-4 py-3 font-semibold text-emerald-700">{money(item.amountCents)}</td><td className="px-4 py-3">{item.status === 'CONFIRMED' ? 'Confirmado' : item.status === 'PENDING' ? 'Pendiente' : item.status === 'CANCELLED' ? 'Cancelado' : item.status}{item.requiresReview ? ' · Requiere revisión' : ''}</td></tr>)}</tbody></table></div></section></>}</div>;
}
